Repository CodeWizardClemens/BSF-bot, pull requests merged in 2023-10, with the labels that each got.

#50 Added relevant information to the BSF-Bot readme
  README.md
Labels: enhancement

#37 Fixed ConversionCog to convert multiple values
  cogs/conversion.py
Labels: bug

#52 Add testcase for infocommands and add DebugCog option
  BSF-bot.py
  README.md
  cogs/info_commands.py
  tests/test_info_commands.py
Labels: documentation, tests

#43 Added delete all weight logs of user
  cogs/weightcog.py
Labels: End-user feature
